package AWS::Lambda::AL;
use 5.026000;
use strict;
use warnings;

our $VERSION = "0.5.4";

# This list is auto generated by authors/update-aws-lambda-al.pl; DO NOT EDIT
our $LAYERS = {
    '5.38' => {
        'af-south-1' => {
            runtime_arn     => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'ap-east-1' => {
            runtime_arn     => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'ap-northeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'ap-northeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'ap-northeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'ap-south-1' => {
            runtime_arn     => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'ap-southeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'ap-southeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'ap-southeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'ca-central-1' => {
            runtime_arn     => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'eu-central-1' => {
            runtime_arn     => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'eu-north-1' => {
            runtime_arn     => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'eu-south-1' => {
            runtime_arn     => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'eu-west-1' => {
            runtime_arn     => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'eu-west-2' => {
            runtime_arn     => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'eu-west-3' => {
            runtime_arn     => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'me-central-1' => {
            runtime_arn     => "arn:aws:lambda:me-central-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:me-central-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'me-south-1' => {
            runtime_arn     => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'sa-east-1' => {
            runtime_arn     => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'us-east-1' => {
            runtime_arn     => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'us-east-2' => {
            runtime_arn     => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'us-west-1' => {
            runtime_arn     => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
        'us-west-2' => {
            runtime_arn     => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-38-runtime:1",
            runtime_version => 1,
            paws_arn        => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-38-paws:1",
            paws_version    => 1,
        },
    },
    '5.36' => {
        'af-south-1' => {
            runtime_arn     => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'ap-east-1' => {
            runtime_arn     => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'ap-northeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'ap-northeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'ap-northeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'ap-south-1' => {
            runtime_arn     => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'ap-southeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'ap-southeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'ap-southeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'ca-central-1' => {
            runtime_arn     => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'eu-central-1' => {
            runtime_arn     => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'eu-north-1' => {
            runtime_arn     => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'eu-south-1' => {
            runtime_arn     => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'eu-west-1' => {
            runtime_arn     => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'eu-west-2' => {
            runtime_arn     => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'eu-west-3' => {
            runtime_arn     => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'me-central-1' => {
            runtime_arn     => "arn:aws:lambda:me-central-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:me-central-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'me-south-1' => {
            runtime_arn     => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'sa-east-1' => {
            runtime_arn     => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'us-east-1' => {
            runtime_arn     => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'us-east-2' => {
            runtime_arn     => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'us-west-1' => {
            runtime_arn     => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
        'us-west-2' => {
            runtime_arn     => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-36-runtime:4",
            runtime_version => 4,
            paws_arn        => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-36-paws:4",
            paws_version    => 4,
        },
    },
    '5.34' => {
        'af-south-1' => {
            runtime_arn     => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-34-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'ap-east-1' => {
            runtime_arn     => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-34-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'ap-northeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-34-runtime:9",
            runtime_version => 9,
            paws_arn        => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'ap-northeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-34-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'ap-northeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-34-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'ap-south-1' => {
            runtime_arn     => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-34-runtime:9",
            runtime_version => 9,
            paws_arn        => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'ap-southeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-34-runtime:9",
            runtime_version => 9,
            paws_arn        => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'ap-southeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-34-runtime:9",
            runtime_version => 9,
            paws_arn        => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'ap-southeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-34-runtime:5",
            runtime_version => 5,
            paws_arn        => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-34-paws:5",
            paws_version    => 5,
        },
        'ca-central-1' => {
            runtime_arn     => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-34-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'eu-central-1' => {
            runtime_arn     => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-34-runtime:9",
            runtime_version => 9,
            paws_arn        => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'eu-north-1' => {
            runtime_arn     => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-34-runtime:6",
            runtime_version => 6,
            paws_arn        => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-34-paws:6",
            paws_version    => 6,
        },
        'eu-south-1' => {
            runtime_arn     => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-34-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'eu-west-1' => {
            runtime_arn     => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-34-runtime:9",
            runtime_version => 9,
            paws_arn        => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'eu-west-2' => {
            runtime_arn     => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-34-runtime:9",
            runtime_version => 9,
            paws_arn        => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'eu-west-3' => {
            runtime_arn     => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-34-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'me-central-1' => {
            runtime_arn     => "arn:aws:lambda:me-central-1:445285296882:layer:perl-5-34-runtime:3",
            runtime_version => 3,
            paws_arn        => "arn:aws:lambda:me-central-1:445285296882:layer:perl-5-34-paws:3",
            paws_version    => 3,
        },
        'me-south-1' => {
            runtime_arn     => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-34-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'sa-east-1' => {
            runtime_arn     => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-34-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'us-east-1' => {
            runtime_arn     => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-34-runtime:9",
            runtime_version => 9,
            paws_arn        => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'us-east-2' => {
            runtime_arn     => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-34-runtime:9",
            runtime_version => 9,
            paws_arn        => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'us-west-1' => {
            runtime_arn     => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-34-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
        'us-west-2' => {
            runtime_arn     => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-34-runtime:9",
            runtime_version => 9,
            paws_arn        => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-34-paws:8",
            paws_version    => 8,
        },
    },
    '5.32' => {
        'af-south-1' => {
            runtime_arn     => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-32-runtime:10",
            runtime_version => 10,
            paws_arn        => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'ap-east-1' => {
            runtime_arn     => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-32-runtime:10",
            runtime_version => 10,
            paws_arn        => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'ap-northeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-32-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'ap-northeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-32-runtime:10",
            runtime_version => 10,
            paws_arn        => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'ap-northeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-32-runtime:8",
            runtime_version => 8,
            paws_arn        => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-32-paws:9",
            paws_version    => 9,
        },
        'ap-south-1' => {
            runtime_arn     => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-32-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'ap-southeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-32-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'ap-southeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-32-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'ap-southeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-32-runtime:5",
            runtime_version => 5,
            paws_arn        => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-32-paws:5",
            paws_version    => 5,
        },
        'ca-central-1' => {
            runtime_arn     => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-32-runtime:10",
            runtime_version => 10,
            paws_arn        => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'eu-central-1' => {
            runtime_arn     => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-32-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'eu-north-1' => {
            runtime_arn     => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-32-runtime:6",
            runtime_version => 6,
            paws_arn        => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-32-paws:6",
            paws_version    => 6,
        },
        'eu-south-1' => {
            runtime_arn     => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-32-runtime:10",
            runtime_version => 10,
            paws_arn        => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'eu-west-1' => {
            runtime_arn     => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-32-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'eu-west-2' => {
            runtime_arn     => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-32-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'eu-west-3' => {
            runtime_arn     => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-32-runtime:10",
            runtime_version => 10,
            paws_arn        => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'me-central-1' => {
            runtime_arn     => "arn:aws:lambda:me-central-1:445285296882:layer:perl-5-32-runtime:3",
            runtime_version => 3,
            paws_arn        => "arn:aws:lambda:me-central-1:445285296882:layer:perl-5-32-paws:3",
            paws_version    => 3,
        },
        'me-south-1' => {
            runtime_arn     => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-32-runtime:10",
            runtime_version => 10,
            paws_arn        => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'sa-east-1' => {
            runtime_arn     => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-32-runtime:10",
            runtime_version => 10,
            paws_arn        => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'us-east-1' => {
            runtime_arn     => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-32-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'us-east-2' => {
            runtime_arn     => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-32-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'us-west-1' => {
            runtime_arn     => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-32-runtime:10",
            runtime_version => 10,
            paws_arn        => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
        'us-west-2' => {
            runtime_arn     => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-32-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-32-paws:11",
            paws_version    => 11,
        },
    },
    '5.30' => {
        'af-south-1' => {
            runtime_arn     => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-30-runtime:7",
            runtime_version => 7,
            paws_arn        => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-30-paws:8",
            paws_version    => 8,
        },
        'ap-east-1' => {
            runtime_arn     => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-30-runtime:14",
            runtime_version => 14,
            paws_arn        => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'ap-northeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-30-runtime:15",
            runtime_version => 15,
            paws_arn        => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'ap-northeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-30-runtime:14",
            runtime_version => 14,
            paws_arn        => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'ap-northeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-30-runtime:5",
            runtime_version => 5,
            paws_arn        => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-30-paws:6",
            paws_version    => 6,
        },
        'ap-south-1' => {
            runtime_arn     => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-30-runtime:15",
            runtime_version => 15,
            paws_arn        => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'ap-southeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-30-runtime:15",
            runtime_version => 15,
            paws_arn        => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'ap-southeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-30-runtime:15",
            runtime_version => 15,
            paws_arn        => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'ap-southeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-30-runtime:2",
            runtime_version => 2,
            paws_arn        => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-30-paws:2",
            paws_version    => 2,
        },
        'ca-central-1' => {
            runtime_arn     => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-30-runtime:14",
            runtime_version => 14,
            paws_arn        => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'eu-central-1' => {
            runtime_arn     => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-30-runtime:15",
            runtime_version => 15,
            paws_arn        => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'eu-north-1' => {
            runtime_arn     => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-30-runtime:3",
            runtime_version => 3,
            paws_arn        => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-30-paws:3",
            paws_version    => 3,
        },
        'eu-south-1' => {
            runtime_arn     => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-30-runtime:7",
            runtime_version => 7,
            paws_arn        => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-30-paws:8",
            paws_version    => 8,
        },
        'eu-west-1' => {
            runtime_arn     => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-30-runtime:15",
            runtime_version => 15,
            paws_arn        => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'eu-west-2' => {
            runtime_arn     => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-30-runtime:15",
            runtime_version => 15,
            paws_arn        => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'eu-west-3' => {
            runtime_arn     => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-30-runtime:14",
            runtime_version => 14,
            paws_arn        => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'me-south-1' => {
            runtime_arn     => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-30-runtime:12",
            runtime_version => 12,
            paws_arn        => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-30-paws:11",
            paws_version    => 11,
        },
        'sa-east-1' => {
            runtime_arn     => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-30-runtime:14",
            runtime_version => 14,
            paws_arn        => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'us-east-1' => {
            runtime_arn     => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-30-runtime:15",
            runtime_version => 15,
            paws_arn        => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'us-east-2' => {
            runtime_arn     => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-30-runtime:15",
            runtime_version => 15,
            paws_arn        => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'us-west-1' => {
            runtime_arn     => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-30-runtime:14",
            runtime_version => 14,
            paws_arn        => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
        'us-west-2' => {
            runtime_arn     => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-30-runtime:15",
            runtime_version => 15,
            paws_arn        => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-30-paws:12",
            paws_version    => 12,
        },
    },
    '5.28' => {
        'af-south-1' => {
            runtime_arn     => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-28-runtime:7",
            runtime_version => 7,
            paws_arn        => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-28-paws:8",
            paws_version    => 8,
        },
        'ap-east-1' => {
            runtime_arn     => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-28-runtime:13",
            runtime_version => 13,
            paws_arn        => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'ap-northeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-28-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'ap-northeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-28-runtime:20",
            runtime_version => 20,
            paws_arn        => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'ap-northeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-28-runtime:5",
            runtime_version => 5,
            paws_arn        => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-28-paws:6",
            paws_version    => 6,
        },
        'ap-south-1' => {
            runtime_arn     => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-28-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'ap-southeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-28-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'ap-southeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-28-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'ap-southeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-28-runtime:2",
            runtime_version => 2,
            paws_arn        => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-28-paws:2",
            paws_version    => 2,
        },
        'ca-central-1' => {
            runtime_arn     => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-28-runtime:20",
            runtime_version => 20,
            paws_arn        => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'eu-central-1' => {
            runtime_arn     => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-28-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'eu-north-1' => {
            runtime_arn     => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-28-runtime:3",
            runtime_version => 3,
            paws_arn        => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-28-paws:3",
            paws_version    => 3,
        },
        'eu-south-1' => {
            runtime_arn     => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-28-runtime:7",
            runtime_version => 7,
            paws_arn        => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-28-paws:8",
            paws_version    => 8,
        },
        'eu-west-1' => {
            runtime_arn     => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-28-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'eu-west-2' => {
            runtime_arn     => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-28-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'eu-west-3' => {
            runtime_arn     => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-28-runtime:20",
            runtime_version => 20,
            paws_arn        => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'me-south-1' => {
            runtime_arn     => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-28-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-28-paws:10",
            paws_version    => 10,
        },
        'sa-east-1' => {
            runtime_arn     => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-28-runtime:20",
            runtime_version => 20,
            paws_arn        => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'us-east-1' => {
            runtime_arn     => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-28-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'us-east-2' => {
            runtime_arn     => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-28-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'us-west-1' => {
            runtime_arn     => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-28-runtime:20",
            runtime_version => 20,
            paws_arn        => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
        'us-west-2' => {
            runtime_arn     => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-28-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-28-paws:11",
            paws_version    => 11,
        },
    },
    '5.26' => {
        'af-south-1' => {
            runtime_arn     => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-26-runtime:7",
            runtime_version => 7,
            paws_arn        => "arn:aws:lambda:af-south-1:445285296882:layer:perl-5-26-paws:8",
            paws_version    => 8,
        },
        'ap-east-1' => {
            runtime_arn     => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-26-runtime:14",
            runtime_version => 14,
            paws_arn        => "arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-26-paws:12",
            paws_version    => 12,
        },
        'ap-northeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-26-runtime:22",
            runtime_version => 22,
            paws_arn        => "arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-26-paws:12",
            paws_version    => 12,
        },
        'ap-northeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-26-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-26-paws:12",
            paws_version    => 12,
        },
        'ap-northeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-26-runtime:5",
            runtime_version => 5,
            paws_arn        => "arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-26-paws:6",
            paws_version    => 6,
        },
        'ap-south-1' => {
            runtime_arn     => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-26-runtime:22",
            runtime_version => 22,
            paws_arn        => "arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-26-paws:12",
            paws_version    => 12,
        },
        'ap-southeast-1' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-26-runtime:22",
            runtime_version => 22,
            paws_arn        => "arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-26-paws:12",
            paws_version    => 12,
        },
        'ap-southeast-2' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-26-runtime:22",
            runtime_version => 22,
            paws_arn        => "arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-26-paws:12",
            paws_version    => 12,
        },
        'ap-southeast-3' => {
            runtime_arn     => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-26-runtime:2",
            runtime_version => 2,
            paws_arn        => "arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-26-paws:2",
            paws_version    => 2,
        },
        'ca-central-1' => {
            runtime_arn     => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-26-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-26-paws:12",
            paws_version    => 12,
        },
        'eu-central-1' => {
            runtime_arn     => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-26-runtime:22",
            runtime_version => 22,
            paws_arn        => "arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-26-paws:12",
            paws_version    => 12,
        },
        'eu-north-1' => {
            runtime_arn     => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-26-runtime:3",
            runtime_version => 3,
            paws_arn        => "arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-26-paws:3",
            paws_version    => 3,
        },
        'eu-south-1' => {
            runtime_arn     => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-26-runtime:7",
            runtime_version => 7,
            paws_arn        => "arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-26-paws:8",
            paws_version    => 8,
        },
        'eu-west-1' => {
            runtime_arn     => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-26-runtime:22",
            runtime_version => 22,
            paws_arn        => "arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-26-paws:12",
            paws_version    => 12,
        },
        'eu-west-2' => {
            runtime_arn     => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-26-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-26-paws:11",
            paws_version    => 11,
        },
        'eu-west-3' => {
            runtime_arn     => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-26-runtime:20",
            runtime_version => 20,
            paws_arn        => "arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-26-paws:11",
            paws_version    => 11,
        },
        'me-south-1' => {
            runtime_arn     => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-26-runtime:11",
            runtime_version => 11,
            paws_arn        => "arn:aws:lambda:me-south-1:445285296882:layer:perl-5-26-paws:10",
            paws_version    => 10,
        },
        'sa-east-1' => {
            runtime_arn     => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-26-runtime:20",
            runtime_version => 20,
            paws_arn        => "arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-26-paws:11",
            paws_version    => 11,
        },
        'us-east-1' => {
            runtime_arn     => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-26-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:us-east-1:445285296882:layer:perl-5-26-paws:11",
            paws_version    => 11,
        },
        'us-east-2' => {
            runtime_arn     => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-26-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:us-east-2:445285296882:layer:perl-5-26-paws:11",
            paws_version    => 11,
        },
        'us-west-1' => {
            runtime_arn     => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-26-runtime:20",
            runtime_version => 20,
            paws_arn        => "arn:aws:lambda:us-west-1:445285296882:layer:perl-5-26-paws:11",
            paws_version    => 11,
        },
        'us-west-2' => {
            runtime_arn     => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-26-runtime:21",
            runtime_version => 21,
            paws_arn        => "arn:aws:lambda:us-west-2:445285296882:layer:perl-5-26-paws:11",
            paws_version    => 11,
        },
    },
};


sub get_layer_info {
    my ($version, $region) = @_;
    return $LAYERS->{$version}{$region};
}

sub print_runtime_arn {
    my ($version, $region) = @_;
    print $LAYERS->{$version}{$region}{runtime_arn};
}

sub print_paws_arn {
    my ($version, $region) = @_;
    print $LAYERS->{$version}{$region}{paws_arn};
}

1;
__END__

=encoding utf-8

=head1 NAME

AWS::Lambda::AL - AWS Lambda Custom Runtimes based on Amazon Linux

=head1 SYNOPSIS

You can get the layer ARN in your script by using C<get_layer_info>.

    use AWS::Lambda::AL;
    my $info = AWS::Lambda::AL::get_layer_info(
        "5.38",      # Perl Version
        "us-east-1", # Region
        "x86_64",    # Architecture ("x86_64" or "arm64", optional, the default is "x86_64")
    );
    say $info->{runtime_arn};     # arn:aws:lambda:us-east-1:445285296882:layer:perl-5-38-runtime:1
    say $info->{runtime_version}; # 1
    say $info->{paws_arn}         # arn:aws:lambda:us-east-1:445285296882:layer:perl-5-38-paws:1
    say $info->{paws_version}     # 1,

Or, you can use following one-liner.

    perl -MAWS::Lambda -e 'AWS::Lambda::AL::print_runtime_arn("5.38", "us-east-1")'
    perl -MAWS::Lambda -e 'AWS::Lambda::AL::print_paws_arn("5.38", "us-east-1")'

The list of all available layer ARN is:

=over

=item Perl 5.38

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:me-central-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-38-runtime:1>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-38-runtime:1>

=back

=item Perl 5.36

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:me-central-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-36-runtime:4>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-36-runtime:4>

=back

=item Perl 5.34

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-34-runtime:8>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-34-runtime:8>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-34-runtime:9>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-34-runtime:8>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-34-runtime:8>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-34-runtime:9>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-34-runtime:9>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-34-runtime:9>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-34-runtime:5>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-34-runtime:8>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-34-runtime:9>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-34-runtime:6>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-34-runtime:8>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-34-runtime:9>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-34-runtime:9>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-34-runtime:8>

=item C<arn:aws:lambda:me-central-1:445285296882:layer:perl-5-34-runtime:3>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-34-runtime:8>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-34-runtime:8>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-34-runtime:9>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-34-runtime:9>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-34-runtime:8>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-34-runtime:9>

=back

=item Perl 5.32

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-32-runtime:10>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-32-runtime:10>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-32-runtime:11>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-32-runtime:10>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-32-runtime:8>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-32-runtime:11>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-32-runtime:11>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-32-runtime:11>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-32-runtime:5>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-32-runtime:10>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-32-runtime:11>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-32-runtime:6>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-32-runtime:10>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-32-runtime:11>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-32-runtime:11>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-32-runtime:10>

=item C<arn:aws:lambda:me-central-1:445285296882:layer:perl-5-32-runtime:3>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-32-runtime:10>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-32-runtime:10>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-32-runtime:11>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-32-runtime:11>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-32-runtime:10>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-32-runtime:11>

=back

=item Perl 5.30

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-30-runtime:7>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-30-runtime:14>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-30-runtime:15>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-30-runtime:14>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-30-runtime:5>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-30-runtime:15>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-30-runtime:15>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-30-runtime:15>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-30-runtime:2>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-30-runtime:14>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-30-runtime:15>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-30-runtime:3>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-30-runtime:7>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-30-runtime:15>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-30-runtime:15>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-30-runtime:14>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-30-runtime:12>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-30-runtime:14>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-30-runtime:15>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-30-runtime:15>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-30-runtime:14>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-30-runtime:15>

=back

=item Perl 5.28

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-28-runtime:7>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-28-runtime:13>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-28-runtime:21>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-28-runtime:20>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-28-runtime:5>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-28-runtime:21>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-28-runtime:21>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-28-runtime:21>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-28-runtime:2>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-28-runtime:20>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-28-runtime:21>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-28-runtime:3>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-28-runtime:7>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-28-runtime:21>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-28-runtime:21>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-28-runtime:20>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-28-runtime:11>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-28-runtime:20>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-28-runtime:21>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-28-runtime:21>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-28-runtime:20>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-28-runtime:21>

=back

=item Perl 5.26

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-26-runtime:7>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-26-runtime:14>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-26-runtime:22>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-26-runtime:21>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-26-runtime:5>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-26-runtime:22>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-26-runtime:22>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-26-runtime:22>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-26-runtime:2>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-26-runtime:21>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-26-runtime:22>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-26-runtime:3>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-26-runtime:7>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-26-runtime:22>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-26-runtime:21>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-26-runtime:20>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-26-runtime:11>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-26-runtime:20>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-26-runtime:21>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-26-runtime:21>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-26-runtime:20>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-26-runtime:21>

=back

=back

And Paws layers:

=over

=item Perl 5.38

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:me-central-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-38-paws:1>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-38-paws:1>

=back

=item Perl 5.36

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:me-central-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-36-paws:4>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-36-paws:4>

=back

=item Perl 5.34

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-34-paws:5>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-34-paws:6>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:me-central-1:445285296882:layer:perl-5-34-paws:3>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-34-paws:8>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-34-paws:8>

=back

=item Perl 5.32

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-32-paws:9>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-32-paws:5>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-32-paws:6>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:me-central-1:445285296882:layer:perl-5-32-paws:3>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-32-paws:11>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-32-paws:11>

=back

=item Perl 5.30

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-30-paws:8>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-30-paws:6>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-30-paws:2>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-30-paws:3>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-30-paws:8>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-30-paws:11>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-30-paws:12>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-30-paws:12>

=back

=item Perl 5.28

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-28-paws:8>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-28-paws:6>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-28-paws:2>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-28-paws:3>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-28-paws:8>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-28-paws:10>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-28-paws:11>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-28-paws:11>

=back

=item Perl 5.26

=over

=item C<arn:aws:lambda:af-south-1:445285296882:layer:perl-5-26-paws:8>

=item C<arn:aws:lambda:ap-east-1:445285296882:layer:perl-5-26-paws:12>

=item C<arn:aws:lambda:ap-northeast-1:445285296882:layer:perl-5-26-paws:12>

=item C<arn:aws:lambda:ap-northeast-2:445285296882:layer:perl-5-26-paws:12>

=item C<arn:aws:lambda:ap-northeast-3:445285296882:layer:perl-5-26-paws:6>

=item C<arn:aws:lambda:ap-south-1:445285296882:layer:perl-5-26-paws:12>

=item C<arn:aws:lambda:ap-southeast-1:445285296882:layer:perl-5-26-paws:12>

=item C<arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-26-paws:12>

=item C<arn:aws:lambda:ap-southeast-3:445285296882:layer:perl-5-26-paws:2>

=item C<arn:aws:lambda:ca-central-1:445285296882:layer:perl-5-26-paws:12>

=item C<arn:aws:lambda:eu-central-1:445285296882:layer:perl-5-26-paws:12>

=item C<arn:aws:lambda:eu-north-1:445285296882:layer:perl-5-26-paws:3>

=item C<arn:aws:lambda:eu-south-1:445285296882:layer:perl-5-26-paws:8>

=item C<arn:aws:lambda:eu-west-1:445285296882:layer:perl-5-26-paws:12>

=item C<arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-26-paws:11>

=item C<arn:aws:lambda:eu-west-3:445285296882:layer:perl-5-26-paws:11>

=item C<arn:aws:lambda:me-south-1:445285296882:layer:perl-5-26-paws:10>

=item C<arn:aws:lambda:sa-east-1:445285296882:layer:perl-5-26-paws:11>

=item C<arn:aws:lambda:us-east-1:445285296882:layer:perl-5-26-paws:11>

=item C<arn:aws:lambda:us-east-2:445285296882:layer:perl-5-26-paws:11>

=item C<arn:aws:lambda:us-west-1:445285296882:layer:perl-5-26-paws:11>

=item C<arn:aws:lambda:us-west-2:445285296882:layer:perl-5-26-paws:11>

=back

=back

=head2 Pre-built Zip Archives for Amazon Linux

URLs of zip archives are:

C<https://shogo82148-lambda-perl-runtime-$REGION.s3.amazonaws.com/perl-$VERSION-runtime.zip>

And Paws:

C<https://shogo82148-lambda-perl-runtime-$REGION.s3.amazonaws.com/perl-$VERSION-paws.zip>

=head2 Pre-installed modules

The following modules are pre-installed for convenience.

=over

=item L<AWS::Lambda>

=item L<AWS::XRay>

=item L<JSON>

=item L<Cpanel::JSON::XS>

=item L<JSON::MaybeXS>

=item L<YAML>

=item L<YAML::Tiny>

=item L<YAML::XS>

=item L<Net::SSLeay>

=item L<IO::Socket::SSL>

=item L<Mozilla::CA>

=back

L<Paws> is optional.

=head1 SEE ALSO

=over

=item L<AWS::Lambda>

=item L<AWS::Lambda::Bootstrap>

=item L<AWS::Lambda::Context>

=item L<AWS::Lambda::PSGI>

=item L<Paws>

=item L<AWS::XRay>

=back

=head1 LICENSE

The MIT License (MIT)

Copyright (C) ICHINOSE Shogo

=head1 AUTHOR

ICHINOSE Shogo

=cut
