name: Build Docker Images

# to follow lambci/lambda
on:
  schedule:
    - cron: "19 14 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          printenv PASSWORD | docker login -u "$USERNAME" --password-stdin
        env:
          USERNAME: ${{ secrets.username }}
          PASSWORD: ${{ secrets.password }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to ECR Public Registry
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w2s0h5h2

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - name: Build and Publish Docker Images
        run: ./author/upload-docker-images.pl build

      - run: docker logout
