name: Build Docker Images on Amazon Linux 2

# to follow lambci/lambda
on:
  schedule:
    - cron: "31 14 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          - "5.32"
        flavor:
          - run
          - build
          - run-paws
          - build-paws
    name: Perl ${{ matrix.perl }} ${{ matrix.flavor}} flavor
    steps:
      - uses: actions/checkout@v1
      - name: build ${{ matrix.flavor}} flavor
        run: docker build -t perl:latest author/${{ matrix.perl }}/${{ matrix.flavor }}.al2
      - name: Publish to the Docker Hub
        run: |
          if echo ${{ matrix.flavor }} | grep -F build; then
            PREFIX="build-"
          else
            PREFIX=""
          fi
          if echo ${{ matrix.flavor }} | grep -F paws; then
            SUFFIX="-paws"
          else
            SUFFIX=""
          fi
          TAG=shogo82148/p5-aws-lambda:${PREFIX}${{ matrix.perl }}${SUFFIX}.al2
          printenv PASSWORD | docker login -u "$USERNAME" --password-stdin
          docker tag perl:latest "$TAG"
          echo "push to $TAG"
          docker push "$TAG"
          docker logout
        env:
          USERNAME: ${{ secrets.username }}
          PASSWORD: ${{ secrets.password }}
