name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        perl:
          - "5.44"
          - "5.42"
          - "5.40"
          - "5.38"
          - "5.36"
          - "5.34"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@3d3cb73ca65d657a809d97eab324d4e4f140bf5e # v1.42.0
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpm
          install-modules-args: --with-develop
      - name: Test
        run: |
          minil test --all
