name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        perl:
          - "5.42"
          - "5.40"
          - "5.38"
          - "5.36"
          - "5.34"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@a198315ec4e9244f206879ea7b63078003aec8a6 # v1.41.1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpm
          install-modules-args: --with-develop
      - name: Test
        run: |
          minil test --all
